// Copyright 2026 Kieran Maynard and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDsaVlopTransparencyJobsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "dsa-vlop-transparency-jobs",
		Short:       "Manage dsa vlop transparency jobs",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDsaVlopTransparencyJobsCancelCmd(flags))
	cmd.AddCommand(newDsaVlopTransparencyJobsGetCmd(flags))
	cmd.AddCommand(newDsaVlopTransparencyJobsListCmd(flags))
	cmd.AddCommand(newDsaVlopTransparencyJobsDownloadCmd(flags))
	cmd.AddCommand(newDsaVlopTransparencyJobsResultCmd(flags))
	return cmd
}
