// Copyright 2026 Kieran Maynard and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"dsa-research-pp-cli/internal/cliutil"
	"github.com/spf13/cobra"
)

func newExploreExploreCmd(flags *rootFlags) *cobra.Command {
	var bodyAggregates string
	var bodyCallbackUrl string
	var bodyDerived string
	var bodyFields string
	var bodyGroupBy string
	var bodyHavingAnd string
	var bodyHavingNot string
	var bodyHavingOr string
	var bodyJoinOn string
	var bodyLegs string
	var bodyMaxCount int
	var bodyQueryAnd string
	var bodyQueryNot string
	var bodyQueryOr string
	var bodySort string
	var bodyTable string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "explore",
		Aliases:     []string{"create"},
		Short:       "Public, synchronous, bounded query for the interactive dashboard.",
		Example:     "  dsa-research-pp-cli explore explore",
		Annotations: map[string]string{"pp:endpoint": "explore.explore", "pp:method": "POST", "pp:path": "/api/explore"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/explore"
			params := map[string]string{}
			var body map[string]any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				body = map[string]any{}
				if bodyAggregates != "" {
					var parsedAggregates any
					if err := json.Unmarshal([]byte(bodyAggregates), &parsedAggregates); err != nil {
						return fmt.Errorf("parsing --aggregates JSON: %w", err)
					}
					body["aggregates"] = parsedAggregates
				}
				if bodyCallbackUrl != "" {
					body["callback_url"] = bodyCallbackUrl
				}
				if bodyDerived != "" {
					var parsedDerived any
					if err := json.Unmarshal([]byte(bodyDerived), &parsedDerived); err != nil {
						return fmt.Errorf("parsing --derived JSON: %w", err)
					}
					body["derived"] = parsedDerived
				}
				if bodyFields != "" {
					body["fields"] = bodyFields
				}
				if bodyGroupBy != "" {
					body["group_by"] = cliutil.SplitCSV(bodyGroupBy)
				}
				{
					nestedHaving := map[string]any{}
					if bodyHavingAnd != "" {
						var parsedHavingAnd any
						if err := json.Unmarshal([]byte(bodyHavingAnd), &parsedHavingAnd); err != nil {
							return fmt.Errorf("parsing --having-and JSON: %w", err)
						}
						nestedHaving["and"] = parsedHavingAnd
					}
					if bodyHavingNot != "" {
						var parsedHavingNot any
						if err := json.Unmarshal([]byte(bodyHavingNot), &parsedHavingNot); err != nil {
							return fmt.Errorf("parsing --having-not JSON: %w", err)
						}
						nestedHaving["not"] = parsedHavingNot
					}
					if bodyHavingOr != "" {
						var parsedHavingOr any
						if err := json.Unmarshal([]byte(bodyHavingOr), &parsedHavingOr); err != nil {
							return fmt.Errorf("parsing --having-or JSON: %w", err)
						}
						nestedHaving["or"] = parsedHavingOr
					}
					if len(nestedHaving) > 0 {
						body["having"] = nestedHaving
					}
				}
				if bodyJoinOn != "" {
					body["join_on"] = cliutil.SplitCSV(bodyJoinOn)
				}
				if bodyLegs != "" {
					body["legs"] = bodyLegs
				}
				if bodyMaxCount != 0 {
					body["max_count"] = bodyMaxCount
				}
				{
					nestedQuery := map[string]any{}
					if bodyQueryAnd != "" {
						var parsedQueryAnd any
						if err := json.Unmarshal([]byte(bodyQueryAnd), &parsedQueryAnd); err != nil {
							return fmt.Errorf("parsing --query-and JSON: %w", err)
						}
						nestedQuery["and"] = parsedQueryAnd
					}
					if bodyQueryNot != "" {
						var parsedQueryNot any
						if err := json.Unmarshal([]byte(bodyQueryNot), &parsedQueryNot); err != nil {
							return fmt.Errorf("parsing --query-not JSON: %w", err)
						}
						nestedQuery["not"] = parsedQueryNot
					}
					if bodyQueryOr != "" {
						var parsedQueryOr any
						if err := json.Unmarshal([]byte(bodyQueryOr), &parsedQueryOr); err != nil {
							return fmt.Errorf("parsing --query-or JSON: %w", err)
						}
						nestedQuery["or"] = parsedQueryOr
					}
					if len(nestedQuery) > 0 {
						body["query"] = nestedQuery
					}
				}
				if bodySort != "" {
					var parsedSort any
					if err := json.Unmarshal([]byte(bodySort), &parsedSort); err != nil {
						return fmt.Errorf("parsing --sort JSON: %w", err)
					}
					body["sort"] = parsedSort
				}
				if bodyTable != "" {
					body["table"] = bodyTable
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "explore", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "explore", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "explore", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "explore", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "explore", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "explore",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "explore", partialFailure.Message))
				}
				return nil
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlags renders the body, then the
			// typed partial-failure exit fires unless --allow-partial-failure
			// downgrades it. Without this guard a partial failure would exit
			// 0 for these output modes — the exact silent-swallow regression
			// the surrounding patch is preventing for asJSON / piped output.
			if perr := printOutputWithFlags(cmd.OutOrStdout(), data, flags); perr != nil {
				return perr
			}
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "explore", partialFailure.Message))
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&bodyAggregates, "aggregates", "", "Aggregate columns.")
	cmd.Flags().StringVar(&bodyCallbackUrl, "callback-url", "", "Optional http(s) webhook POSTed (HMAC-signed) when the job finishes.")
	cmd.Flags().StringVar(&bodyDerived, "derived", "", "Computed columns over leg aggregates (composite queries only).")
	cmd.Flags().StringVar(&bodyFields, "fields", "", "Columns to return for a raw (non-aggregated) query. Defaults to all fields.")
	cmd.Flags().StringVar(&bodyGroupBy, "group-by", "", "Dimension fields to group by.")
	cmd.Flags().StringVar(&bodyHavingAnd, "having-and", "", "And")
	cmd.Flags().StringVar(&bodyHavingNot, "having-not", "", "Not")
	cmd.Flags().StringVar(&bodyHavingOr, "having-or", "", "Or")
	cmd.Flags().StringVar(&bodyJoinOn, "join-on", "", "Dimensions to merge legs on; must be a dimension of every leg's table.")
	cmd.Flags().StringVar(&bodyLegs, "legs", "", "Composite query: named single-table sub-queries to merge (2–4; leg names are letters/digits/underscores).")
	cmd.Flags().IntVar(&bodyMaxCount, "max-count", 100, "Row limit (capped at ROW_LIMIT).")
	cmd.Flags().StringVar(&bodyQueryAnd, "query-and", "", "And")
	cmd.Flags().StringVar(&bodyQueryNot, "query-not", "", "Not")
	cmd.Flags().StringVar(&bodyQueryOr, "query-or", "", "Or")
	cmd.Flags().StringVar(&bodySort, "sort", "", "Result ordering.")
	cmd.Flags().StringVar(&bodyTable, "table", "", "Which DSA report table to query (see GET /tables).")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
