// Copyright 2026 Kieran Maynard and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPortalCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "portal",
		Short:       "Get, create, and delete portal",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPortalPageCmd(flags))
	cmd.AddCommand(newPortalRegisterCmd(flags))
	cmd.AddCommand(newPortalRevokeKeyCmd(flags))
	return cmd
}
