// Copyright 2026 Kieran Maynard and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"dsa-research-pp-cli/internal/cliutil"
	"github.com/spf13/cobra"
)

func newQueryPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAggregates string
	var bodyCallbackUrl string
	var bodyDerived string
	var bodyFields string
	var bodyGroupBy string
	var bodyHavingAnd string
	var bodyHavingNot string
	var bodyHavingOr string
	var bodyJoinOn string
	var bodyLegs string
	var bodyMaxCount int
	var bodyQueryAnd string
	var bodyQueryNot string
	var bodyQueryOr string
	var bodySort string
	var bodyTable string

	cmd := &cobra.Command{
		Use:         "query",
		Short:       "Submit Query",
		Long:        "Submit Query",
		Example:     "  dsa-research-pp-cli query",
		Annotations: map[string]string{"pp:endpoint": "query.submit", "pp:method": "POST", "pp:path": "/api/query"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/query"
			params := map[string]string{}
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAggregates != "" {
				var parsedAggregates any
				if err := json.Unmarshal([]byte(bodyAggregates), &parsedAggregates); err != nil {
					return fmt.Errorf("parsing --aggregates JSON: %w", err)
				}
				body["aggregates"] = parsedAggregates
			}
			if bodyCallbackUrl != "" {
				body["callback_url"] = bodyCallbackUrl
			}
			if bodyDerived != "" {
				var parsedDerived any
				if err := json.Unmarshal([]byte(bodyDerived), &parsedDerived); err != nil {
					return fmt.Errorf("parsing --derived JSON: %w", err)
				}
				body["derived"] = parsedDerived
			}
			if bodyFields != "" {
				body["fields"] = bodyFields
			}
			if bodyGroupBy != "" {
				body["group_by"] = cliutil.SplitCSV(bodyGroupBy)
			}
			{
				nestedHaving := map[string]any{}
				if bodyHavingAnd != "" {
					var parsedHavingAnd any
					if err := json.Unmarshal([]byte(bodyHavingAnd), &parsedHavingAnd); err != nil {
						return fmt.Errorf("parsing --having-and JSON: %w", err)
					}
					nestedHaving["and"] = parsedHavingAnd
				}
				if bodyHavingNot != "" {
					var parsedHavingNot any
					if err := json.Unmarshal([]byte(bodyHavingNot), &parsedHavingNot); err != nil {
						return fmt.Errorf("parsing --having-not JSON: %w", err)
					}
					nestedHaving["not"] = parsedHavingNot
				}
				if bodyHavingOr != "" {
					var parsedHavingOr any
					if err := json.Unmarshal([]byte(bodyHavingOr), &parsedHavingOr); err != nil {
						return fmt.Errorf("parsing --having-or JSON: %w", err)
					}
					nestedHaving["or"] = parsedHavingOr
				}
				if len(nestedHaving) > 0 {
					body["having"] = nestedHaving
				}
			}
			if bodyJoinOn != "" {
				body["join_on"] = cliutil.SplitCSV(bodyJoinOn)
			}
			if bodyLegs != "" {
				body["legs"] = bodyLegs
			}
			if bodyMaxCount != 0 {
				body["max_count"] = bodyMaxCount
			}
			{
				nestedQuery := map[string]any{}
				if bodyQueryAnd != "" {
					var parsedQueryAnd any
					if err := json.Unmarshal([]byte(bodyQueryAnd), &parsedQueryAnd); err != nil {
						return fmt.Errorf("parsing --query-and JSON: %w", err)
					}
					nestedQuery["and"] = parsedQueryAnd
				}
				if bodyQueryNot != "" {
					var parsedQueryNot any
					if err := json.Unmarshal([]byte(bodyQueryNot), &parsedQueryNot); err != nil {
						return fmt.Errorf("parsing --query-not JSON: %w", err)
					}
					nestedQuery["not"] = parsedQueryNot
				}
				if bodyQueryOr != "" {
					var parsedQueryOr any
					if err := json.Unmarshal([]byte(bodyQueryOr), &parsedQueryOr); err != nil {
						return fmt.Errorf("parsing --query-or JSON: %w", err)
					}
					nestedQuery["or"] = parsedQueryOr
				}
				if len(nestedQuery) > 0 {
					body["query"] = nestedQuery
				}
			}
			if bodySort != "" {
				var parsedSort any
				if err := json.Unmarshal([]byte(bodySort), &parsedSort); err != nil {
					return fmt.Errorf("parsing --sort JSON: %w", err)
				}
				body["sort"] = parsedSort
			}
			if bodyTable != "" {
				body["table"] = bodyTable
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)

			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "query", data, "")
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAggregates, "aggregates", "", "Aggregate columns.")
	cmd.Flags().StringVar(&bodyCallbackUrl, "callback-url", "", "Optional http(s) webhook POSTed (HMAC-signed) when the job finishes.")
	cmd.Flags().StringVar(&bodyDerived, "derived", "", "Computed columns over leg aggregates (composite queries only).")
	cmd.Flags().StringVar(&bodyFields, "fields", "", "Columns to return for a raw (non-aggregated) query. Defaults to all fields.")
	cmd.Flags().StringVar(&bodyGroupBy, "group-by", "", "Dimension fields to group by.")
	cmd.Flags().StringVar(&bodyHavingAnd, "having-and", "", "And")
	cmd.Flags().StringVar(&bodyHavingNot, "having-not", "", "Not")
	cmd.Flags().StringVar(&bodyHavingOr, "having-or", "", "Or")
	cmd.Flags().StringVar(&bodyJoinOn, "join-on", "", "Dimensions to merge legs on; must be a dimension of every leg's table.")
	cmd.Flags().StringVar(&bodyLegs, "legs", "", "Composite query: named single-table sub-queries to merge (2–4; leg names are letters/digits/underscores).")
	cmd.Flags().IntVar(&bodyMaxCount, "max-count", 100, "Row limit (capped at ROW_LIMIT).")
	cmd.Flags().StringVar(&bodyQueryAnd, "query-and", "", "And")
	cmd.Flags().StringVar(&bodyQueryNot, "query-not", "", "Not")
	cmd.Flags().StringVar(&bodyQueryOr, "query-or", "", "Or")
	cmd.Flags().StringVar(&bodySort, "sort", "", "Result ordering.")
	cmd.Flags().StringVar(&bodyTable, "table", "", "Which DSA report table to query (see GET /tables).")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
