// Copyright 2026 Kieran Maynard and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type Aggregate struct {
	Alias     string `json:"alias"`
	FieldName string `json:"field_name"`
	Function  string `json:"function"`
}

type AskRequest struct {
	Question string `json:"question"`
}

type BooleanQuery struct {
	And json.RawMessage `json:"and"`
	Not json.RawMessage `json:"not"`
	Or  json.RawMessage `json:"or"`
}

type Condition struct {
	FieldName   string          `json:"field_name"`
	FieldValues json.RawMessage `json:"field_values"`
	Operation   string          `json:"operation"`
}

type DerivedColumn struct {
	Alias string `json:"alias"`
	Expr  string `json:"expr"`
}

type GoogleAuthRequest struct {
	Credential string `json:"credential"`
}

type HTTPValidationError struct {
	Detail json.RawMessage `json:"detail"`
}

type Leg struct {
	Aggregates json.RawMessage `json:"aggregates"`
	Query      json.RawMessage `json:"query"`
	Table      string          `json:"table"`
}

type QueryRequest struct {
	Aggregates  json.RawMessage `json:"aggregates"`
	CallbackUrl string          `json:"callback_url"`
	Derived     json.RawMessage `json:"derived"`
	Fields      string          `json:"fields"`
	GroupBy     json.RawMessage `json:"group_by"`
	Having      json.RawMessage `json:"having"`
	JoinOn      json.RawMessage `json:"join_on"`
	Legs        string          `json:"legs"`
	MaxCount    int             `json:"max_count"`
	Query       json.RawMessage `json:"query"`
	Sort        json.RawMessage `json:"sort"`
	Table       string          `json:"table"`
}

type RegisterRequest struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

type Sort struct {
	FieldName string `json:"field_name"`
	Order     string `json:"order"`
}

type ValidationError struct {
	Loc  json.RawMessage `json:"loc"`
	Msg  string          `json:"msg"`
	Type string          `json:"type"`
}
