// Copyright 2026 Kieran Maynard and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"dsa-research-pp-cli/internal/cli"
	"dsa-research-pp-cli/internal/client"
	"dsa-research-pp-cli/internal/cliutil"
	"dsa-research-pp-cli/internal/config"
	"dsa-research-pp-cli/internal/mcp/cobratree"
	"dsa-research-pp-cli/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

const (
	mcpToolResultMaxBytes = 60000
	mcpToolResultMaxItems = 50
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("admin_approve-registration",
			mcplib.WithDescription("Restore (or pre-create) an approved account — e.g. to undo a revoke. Required: email. Returns the new ResponseApproveRegistrationApiAdminRegistrationsEmailApprovePost."),
			mcplib.WithString("email", mcplib.Required(), mcplib.Description("Email")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/admin/registrations/{email}/approve", false, false, nil, []mcpParamBinding{{PublicName: "email", WireName: "email", Location: "path"}}, []string{"email"}),
	)
	s.AddTool(
		mcplib.NewTool("admin_list-registrations",
			mcplib.WithDescription("List researcher registrations, optionally filtered by status. Optional: status. Returns the ResponseListRegistrationsApiAdminRegistrationsGet."),
			mcplib.WithString("status", mcplib.Description("Status")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/admin/registrations", true, false, nil, []mcpParamBinding{{PublicName: "status", WireName: "status", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("admin_revoke-registration",
			mcplib.WithDescription("Revoke an account's access (its live sessions stop working immediately). Required: email. Returns the new ResponseRevokeRegistrationApiAdminRegistrationsEmailRevokePost."),
			mcplib.WithString("email", mcplib.Required(), mcplib.Description("Email")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/admin/registrations/{email}/revoke", false, false, nil, []mcpParamBinding{{PublicName: "email", WireName: "email", Location: "path"}}, []string{"email"}),
	)
	s.AddTool(
		mcplib.NewTool("ask_ask",
			mcplib.WithDescription("Authenticated natural-language query: an LLM translates the question into the *structured* QueryRequest (never SQL), which is then run through the exact same compile_query trust boundary as /api/explore. The model only proposes — a bad field is a 400, and no model-authored SQL can reach the database. Requires an API key (sign in to get one) — LLM calls cost money, so this is gated and rate-limited per key. Disabled (503) unless ANTHROPIC_API_KEY is set. Required: question. Returns the new ResponseAskApiAskPost."),
			mcplib.WithString("question", mcplib.Required(), mcplib.Description("A natural-language question about the DSA VLOP data.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/ask", false, false, nil, []mcpParamBinding{{PublicName: "question", WireName: "question", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("dsa-vlop-transparency-api_root",
			mcplib.WithDescription("Root. Returns the ResponseRootApiGet."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("dsa-vlop-transparency-auth_google",
			mcplib.WithDescription("Auth Google. Required: credential. Returns the new ResponseAuthGoogleApiAuthGooglePost."),
			mcplib.WithString("credential", mcplib.Required(), mcplib.Description("Google ID token (JWT) from Google Identity Services / FedCM.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/auth/google", false, false, nil, []mcpParamBinding{{PublicName: "credential", WireName: "credential", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("dsa-vlop-transparency-jobs_cancel",
			mcplib.WithDescription("Cancel Job. Required: job_id. Returns the ResponseCancelJobApiJobsJobIdDelete. Destructive."),
			mcplib.WithString("job_id", mcplib.Required(), mcplib.Description("Job id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/jobs/{job_id}", false, false, nil, []mcpParamBinding{{PublicName: "job_id", WireName: "job_id", Location: "path"}}, []string{"job_id"}),
	)
	s.AddTool(
		mcplib.NewTool("dsa-vlop-transparency-jobs_get",
			mcplib.WithDescription("Get Job. Required: job_id. Returns the ResponseGetJobApiJobsJobIdGet."),
			mcplib.WithString("job_id", mcplib.Required(), mcplib.Description("Job id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/jobs/{job_id}", true, false, nil, []mcpParamBinding{{PublicName: "job_id", WireName: "job_id", Location: "path"}}, []string{"job_id"}),
	)
	s.AddTool(
		mcplib.NewTool("dsa-vlop-transparency-jobs_list",
			mcplib.WithDescription("List Jobs. Optional: limit (default: 50). Returns the ResponseListJobsApiJobsGet."),
			mcplib.WithNumber("limit", mcplib.Description("Limit")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/jobs", true, false, nil, []mcpParamBinding{{PublicName: "limit", WireName: "limit", Location: "query", Default: "50"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("dsa-vlop-transparency-jobs_download_job-result",
			mcplib.WithDescription("Secure download via a signed, expiring URL — no API key needed. The link is a capability: the HMAC signature authorises this exact job + format + expiry, so possession of a valid, unexpired URL is sufficient. Required: job_id, expires, sig. Optional: format (default: json)."),
			mcplib.WithString("job_id", mcplib.Required(), mcplib.Description("Job id")),
			mcplib.WithNumber("expires", mcplib.Required(), mcplib.Description("Expires")),
			mcplib.WithString("sig", mcplib.Required(), mcplib.Description("Sig")),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/jobs/{job_id}/download", true, false, nil, []mcpParamBinding{{PublicName: "job_id", WireName: "job_id", Location: "path"}, {PublicName: "expires", WireName: "expires", Location: "query"}, {PublicName: "sig", WireName: "sig", Location: "query"}, {PublicName: "format", WireName: "format", Location: "query", Default: "json"}}, []string{"job_id"}),
	)
	s.AddTool(
		mcplib.NewTool("dsa-vlop-transparency-jobs_result_get-job",
			mcplib.WithDescription("Get Job Result. Required: job_id. Optional: format (default: json)."),
			mcplib.WithString("job_id", mcplib.Required(), mcplib.Description("Job id")),
			mcplib.WithString("format", mcplib.Description("Format")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/jobs/{job_id}/result", true, false, nil, []mcpParamBinding{{PublicName: "job_id", WireName: "job_id", Location: "path"}, {PublicName: "format", WireName: "format", Location: "query", Default: "json"}}, []string{"job_id"}),
	)
	s.AddTool(
		mcplib.NewTool("dsa-vlop-transparency-version_version",
			mcplib.WithDescription("The deployed build (commit SHA on Cloud Run, else 'dev') + app version. Returns the ResponseVersionVersionGet."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/version", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("explore_explore",
			mcplib.WithDescription("Public, synchronous, bounded query for the interactive dashboard. Same validated structured-query model as POST /api/query (no SQL is ever accepted; every field/operation is checked against the table registry and all values are bound), but it runs inline and hard-caps the row count — no auth, no job, no webhook. IP-rate-limited so the open endpoint can't be hammered. Optional: aggregates, callback_url, derived (plus 9 more). Returns the new ResponseExploreApiExplorePost."),
			mcplib.WithString("aggregates", mcplib.Description("Aggregate columns.")),
			mcplib.WithString("callback_url", mcplib.Description("Optional http(s) webhook POSTed (HMAC-signed) when the job finishes.")),
			mcplib.WithString("derived", mcplib.Description("Computed columns over leg aggregates (composite queries only).")),
			mcplib.WithString("fields", mcplib.Description("Columns to return for a raw (non-aggregated) query. Defaults to all fields.")),
			mcplib.WithString("group_by", mcplib.Description("Dimension fields to group by.")),
			mcplib.WithString("having-and", mcplib.Description("And")),
			mcplib.WithString("having-not", mcplib.Description("Not")),
			mcplib.WithString("having-or", mcplib.Description("Or")),
			mcplib.WithString("join_on", mcplib.Description("Dimensions to merge legs on; must be a dimension of every leg's table.")),
			mcplib.WithString("legs", mcplib.Description("Composite query: named single-table sub-queries to merge (2–4; leg names are letters/digits/underscores).")),
			mcplib.WithNumber("max_count", mcplib.Description("Row limit (capped at ROW_LIMIT).")),
			mcplib.WithString("query-and", mcplib.Description("And")),
			mcplib.WithString("query-not", mcplib.Description("Not")),
			mcplib.WithString("query-or", mcplib.Description("Or")),
			mcplib.WithString("sort", mcplib.Description("Result ordering.")),
			mcplib.WithString("table", mcplib.Description("Which DSA report table to query (see GET /tables).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/explore", false, false, nil, []mcpParamBinding{{PublicName: "aggregates", WireName: "aggregates", Location: "body"}, {PublicName: "callback_url", WireName: "callback_url", Location: "body"}, {PublicName: "derived", WireName: "derived", Location: "body"}, {PublicName: "fields", WireName: "fields", Location: "body"}, {PublicName: "group_by", WireName: "group_by", Location: "body"}, {PublicName: "having-and", WireName: "and", Location: "body", BodyPath: []string{"having", "and"}}, {PublicName: "having-not", WireName: "not", Location: "body", BodyPath: []string{"having", "not"}}, {PublicName: "having-or", WireName: "or", Location: "body", BodyPath: []string{"having", "or"}}, {PublicName: "join_on", WireName: "join_on", Location: "body"}, {PublicName: "legs", WireName: "legs", Location: "body"}, {PublicName: "max_count", WireName: "max_count", Location: "body"}, {PublicName: "query-and", WireName: "and", Location: "body", BodyPath: []string{"query", "and"}}, {PublicName: "query-not", WireName: "not", Location: "body", BodyPath: []string{"query", "not"}}, {PublicName: "query-or", WireName: "or", Location: "body", BodyPath: []string{"query", "or"}}, {PublicName: "sort", WireName: "sort", Location: "body"}, {PublicName: "table", WireName: "table", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("explore_options",
			mcplib.WithDescription("Public metadata for the dashboard's query builder: each table's queryable dimensions and measures, from the fixed registry (no DB, no secrets). Returns the ResponseExploreOptionsApiExploreOptionsGet."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/explore/options", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("fields_list",
			mcplib.WithDescription("Fields for a report table (`?table=…`), or an overview of all tables. Optional: table. Returns the ResponseListFieldsApiFieldsGet."),
			mcplib.WithString("table", mcplib.Description("Table")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/fields", true, false, nil, []mcpParamBinding{{PublicName: "table", WireName: "table", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("healthz_health",
			mcplib.WithDescription("Health. Returns the ResponseHealthHealthzGet."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/healthz", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("metrics_metrics",
			mcplib.WithDescription("Prometheus metrics. No auth — scrape over an internal network only."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/metrics", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("overview_overview",
			mcplib.WithDescription("Public headline aggregates for the dashboard — no auth. Memoised: the read-only DB is static, so we compute the fixed queries once (no user input reaches SQL) and serve from memory thereafter. Returns the ResponseOverviewApiOverviewGet."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/overview", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("portal_page",
			mcplib.WithDescription("Serve the researcher portal single-page app."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/portal", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("portal_register",
			mcplib.WithDescription("Issue a demo API key for a researcher (no real authentication). Required: email, name. Returns the new ResponsePortalRegisterApiPortalRegisterPost."),
			mcplib.WithString("email", mcplib.Required(), mcplib.Description("Contact email.")),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Researcher's name.")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/portal/register", false, false, nil, []mcpParamBinding{{PublicName: "email", WireName: "email", Location: "body"}, {PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("portal_revoke-key",
			mcplib.WithDescription("Revoke the calling key/session (configured demo keys can't be revoked). Returns the ResponseRevokeKeyApiPortalKeyDelete. Destructive."),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/portal/key", false, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("query_submit",
			mcplib.WithDescription("Submit Query. Optional: aggregates, callback_url, derived (plus 9 more). Returns the new ResponseSubmitQueryApiQueryPost."),
			mcplib.WithString("aggregates", mcplib.Description("Aggregate columns.")),
			mcplib.WithString("callback_url", mcplib.Description("Optional http(s) webhook POSTed (HMAC-signed) when the job finishes.")),
			mcplib.WithString("derived", mcplib.Description("Computed columns over leg aggregates (composite queries only).")),
			mcplib.WithString("fields", mcplib.Description("Columns to return for a raw (non-aggregated) query. Defaults to all fields.")),
			mcplib.WithString("group_by", mcplib.Description("Dimension fields to group by.")),
			mcplib.WithString("having-and", mcplib.Description("And")),
			mcplib.WithString("having-not", mcplib.Description("Not")),
			mcplib.WithString("having-or", mcplib.Description("Or")),
			mcplib.WithString("join_on", mcplib.Description("Dimensions to merge legs on; must be a dimension of every leg's table.")),
			mcplib.WithString("legs", mcplib.Description("Composite query: named single-table sub-queries to merge (2–4; leg names are letters/digits/underscores).")),
			mcplib.WithNumber("max_count", mcplib.Description("Row limit (capped at ROW_LIMIT).")),
			mcplib.WithString("query-and", mcplib.Description("And")),
			mcplib.WithString("query-not", mcplib.Description("Not")),
			mcplib.WithString("query-or", mcplib.Description("Or")),
			mcplib.WithString("sort", mcplib.Description("Result ordering.")),
			mcplib.WithString("table", mcplib.Description("Which DSA report table to query (see GET /tables).")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/query", false, false, nil, []mcpParamBinding{{PublicName: "aggregates", WireName: "aggregates", Location: "body"}, {PublicName: "callback_url", WireName: "callback_url", Location: "body"}, {PublicName: "derived", WireName: "derived", Location: "body"}, {PublicName: "fields", WireName: "fields", Location: "body"}, {PublicName: "group_by", WireName: "group_by", Location: "body"}, {PublicName: "having-and", WireName: "and", Location: "body", BodyPath: []string{"having", "and"}}, {PublicName: "having-not", WireName: "not", Location: "body", BodyPath: []string{"having", "not"}}, {PublicName: "having-or", WireName: "or", Location: "body", BodyPath: []string{"having", "or"}}, {PublicName: "join_on", WireName: "join_on", Location: "body"}, {PublicName: "legs", WireName: "legs", Location: "body"}, {PublicName: "max_count", WireName: "max_count", Location: "body"}, {PublicName: "query-and", WireName: "and", Location: "body", BodyPath: []string{"query", "and"}}, {PublicName: "query-not", WireName: "not", Location: "body", BodyPath: []string{"query", "not"}}, {PublicName: "query-or", WireName: "or", Location: "body", BodyPath: []string{"query", "or"}}, {PublicName: "sort", WireName: "sort", Location: "body"}, {PublicName: "table", WireName: "table", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("readyz_ready",
			mcplib.WithDescription("Ready. Returns the ResponseReadyReadyzGet."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/readyz", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("schema_table",
			mcplib.WithDescription("The queryable field registry (dimensions + measures) for a report table. Required: table. Returns the ResponseTableSchemaApiSchemaTableGet."),
			mcplib.WithString("table", mcplib.Required(), mcplib.Description("Table")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/schema/{table}", true, false, nil, []mcpParamBinding{{PublicName: "table", WireName: "table", Location: "path"}}, []string{"table"}),
	)
	s.AddTool(
		mcplib.NewTool("static_vendored-asset",
			mcplib.WithDescription("Serve a vendored third-party asset (e.g. Chart.js) from static/vendor. Required: filename."),
			mcplib.WithString("filename", mcplib.Required(), mcplib.Description("Filename")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/static/vendor/{filename}", true, false, nil, []mcpParamBinding{{PublicName: "filename", WireName: "filename", Location: "path"}}, []string{"filename"}),
	)
	s.AddTool(
		mcplib.NewTool("tables_list",
			mcplib.WithDescription("The queryable DSA report tables and the dataset's reporting period. Returns the ResponseListTablesApiTablesGet."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/tables", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='items'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
	BodyPath   []string
	Default    string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		return fmt.Sprintf("%v", v)
	}
}
func setNestedBodyArg(body map[string]any, path []string, value any) {
	if len(path) == 0 {
		return
	}
	if len(path) == 1 {
		body[path[0]] = value
		return
	}
	current := body
	for _, key := range path[:len(path)-1] {
		next, ok := current[key].(map[string]any)
		if !ok {
			next = map[string]any{}
			current[key] = next
		}
		current = next
	}
	current[path[len(path)-1]] = value
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				if binding.Default != "" {
					v = binding.Default
				} else {
					continue
				}
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			case "body":
				if len(binding.BodyPath) > 0 {
					setNestedBodyArg(bodyArgs, binding.BodyPath, v)
				} else {
					bodyArgs[binding.WireName] = v
				}
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
		case "PATCH":
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export DSA_RESEARCH_APIKEY_HEADER=<your-key>" +
					"\n      Run 'dsa-research-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your API key." +
					"\n      Set it with: export DSA_RESEARCH_APIKEY_HEADER=<your-key>" +
					"\n      Run 'dsa-research-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export DSA_RESEARCH_APIKEY_HEADER=<your-key>" +
					"\n      Run 'dsa-research-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcpToolResultText(method, data), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	trimmed := strings.TrimSpace(string(data))
	if strings.EqualFold(method, "GET") && len(trimmed) > 0 && trimmed[0] == '[' {
		var items []json.RawMessage
		if json.Unmarshal(data, &items) == nil {
			return mcplib.NewToolResultText(string(mcpBoundedListEnvelope("items", items, len(data))))
		}
	}
	if len(data) <= mcpToolResultMaxBytes {
		return mcplib.NewToolResultText(string(data))
	}
	if strings.EqualFold(method, "GET") {
		if out, ok := mcpBoundedSingleArrayObject(data); ok {
			return mcplib.NewToolResultText(string(out))
		}
	}
	return mcplib.NewToolResultText(string(mcpOversizedPreviewEnvelope(data)))
}

func mcpBoundedSingleArrayObject(data json.RawMessage) ([]byte, bool) {
	var obj map[string]json.RawMessage
	if json.Unmarshal(data, &obj) != nil {
		return nil, false
	}
	arrayField := ""
	var items []json.RawMessage
	for key, raw := range obj {
		trimmed := strings.TrimSpace(string(raw))
		if len(trimmed) == 0 || trimmed[0] != '[' {
			continue
		}
		var candidate []json.RawMessage
		if json.Unmarshal(raw, &candidate) != nil {
			continue
		}
		if arrayField != "" {
			return nil, false
		}
		arrayField = key
		items = candidate
	}
	if arrayField == "" {
		return nil, false
	}
	build := func(subset []json.RawMessage) any {
		out := make(map[string]any, len(obj)+6)
		for key, raw := range obj {
			if key == arrayField {
				out[key] = subset
				continue
			}
			out[key] = raw
		}
		if len(subset) < len(items) {
			out["_pp_truncated"] = true
			out["_pp_total_count"] = len(items)
			out["_pp_returned_count"] = len(subset)
			out["_pp_original_bytes"] = len(data)
			out["_pp_max_bytes"] = mcpToolResultMaxBytes
			out["_pp_note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	out := mcpFitJSONItems(items, build)
	if len(out) > mcpToolResultMaxBytes {
		return nil, false
	}
	return out, true
}

func mcpBoundedListEnvelope(field string, items []json.RawMessage, originalBytes int) []byte {
	build := func(subset []json.RawMessage) any {
		out := map[string]any{
			"count": len(items),
			field:   subset,
		}
		if len(subset) < len(items) {
			out["truncated"] = true
			out["returned_count"] = len(subset)
			out["original_bytes"] = originalBytes
			out["max_bytes"] = mcpToolResultMaxBytes
			out["note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	return mcpFitJSONItems(items, build)
}

func mcpFitJSONItems(items []json.RawMessage, build func([]json.RawMessage) any) []byte {
	limit := len(items)
	if limit > mcpToolResultMaxItems {
		limit = mcpToolResultMaxItems
	}
	for n := limit; n >= 0; n-- {
		out, err := json.Marshal(build(items[:n]))
		if err != nil {
			continue
		}
		if len(out) <= mcpToolResultMaxBytes || n == 0 {
			return out
		}
	}
	out, _ := json.Marshal(build(items[:0]))
	return out
}

func mcpOversizedPreviewEnvelope(data json.RawMessage) []byte {
	previewBytes := data
	if len(previewBytes) > 4000 {
		previewBytes = previewBytes[:4000]
	}
	out, _ := json.Marshal(map[string]any{
		"truncated":      true,
		"original_bytes": len(data),
		"max_bytes":      mcpToolResultMaxBytes,
		"preview":        string(previewBytes),
		"note":           "Typed MCP endpoint response exceeded the tool result budget and was not a recognized list envelope. Narrow the request with filters, search/sql, or a command-mirror tool with --agent/--compact/--select.",
	})
	return out
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "dsa-research-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "dsa-research-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	return toolResultJSON(results)
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}

	return toolResultJSON(results)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "dsa-research",
		"description": "Query the aggregated EU Digital Services Act VLOP transparency reports (tables 3–11) with structured parameters (no SQL)",
		"archetype":   "communication",
		"tool_count":  26,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion dsa-research-pp-cli binary.",
		"auth": map[string]any{
			"type": "api_key",
			"env_vars": []map[string]any{
				{
					"name":        "DSA_RESEARCH_APIKEY_HEADER",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "admin",
				"description": "Manage admin",
				"endpoints":   []string{"approve-registration", "list-registrations", "revoke-registration"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "ask",
				"description": "Manage ask",
				"endpoints":   []string{"ask"},
				"searchable":  true,
			},
			{
				"name":        "dsa-vlop-transparency-api",
				"description": "Manage dsa vlop transparency api",
				"endpoints":   []string{"root"},
				"syncable":    true,
			},
			{
				"name":        "dsa-vlop-transparency-auth",
				"description": "Manage dsa vlop transparency auth",
				"endpoints":   []string{"google"},
				"searchable":  true,
			},
			{
				"name":        "dsa-vlop-transparency-jobs",
				"description": "Manage dsa vlop transparency jobs",
				"endpoints":   []string{"cancel", "get", "list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "dsa-vlop-transparency-version",
				"description": "Manage dsa vlop transparency version",
				"endpoints":   []string{"version"},
				"syncable":    true,
			},
			{
				"name":        "explore",
				"description": "Manage explore",
				"endpoints":   []string{"explore", "options"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "fields",
				"description": "Manage fields",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "healthz",
				"description": "Manage healthz",
				"endpoints":   []string{"health"},
				"syncable":    true,
			},
			{
				"name":        "metrics",
				"description": "Manage metrics",
				"endpoints":   []string{"metrics"},
			},
			{
				"name":        "overview",
				"description": "Manage overview",
				"endpoints":   []string{"overview"},
				"syncable":    true,
			},
			{
				"name":        "portal",
				"description": "Manage portal",
				"endpoints":   []string{"page", "register", "revoke-key"},
				"searchable":  true,
			},
			{
				"name":        "query",
				"description": "Manage query",
				"endpoints":   []string{"submit"},
				"searchable":  true,
			},
			{
				"name":        "readyz",
				"description": "Manage readyz",
				"endpoints":   []string{"ready"},
				"syncable":    true,
			},
			{
				"name":        "schema",
				"description": "Manage schema",
				"endpoints":   []string{"table"},
				"searchable":  true,
			},
			{
				"name":        "static",
				"description": "Manage static",
				"endpoints":   []string{"vendored-asset"},
				"searchable":  true,
			},
			{
				"name":        "tables",
				"description": "Manage tables",
				"endpoints":   []string{"list"},
				"syncable":    true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		"playbook": []map[string]string{
			{"topic": "Message search", "insight": "Use the search tool on synced data rather than paginating through message history. Message APIs often have aggressive rate limits."},
			{"topic": "Channel health", "insight": "When analyzing channel activity, use the channel-health command or sql aggregation on synced messages. Don't iterate individual messages via API."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
